spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=5d9e1eba3b793c0f72ab6a16955230c05080d9bc0f48ea02f3e0bf9a2b78e001f94f372540af15fbfbc14447f5fc9ec559a51cc501dff944273a64e2ec496e4c
jwt.expiration=86400000